### ISSUE TITLE
Remove "Reset Role Selection" button in role-select-menus

### ISSUE THREAD

**Issue by TannerKvarfordt** [TannerKvarfordt/Kard-bot#54]
The "Reset Role Selection" button is no longer necessary as of [bwmarrin/discordgo:v0.24.0](https://github.com/bwmarrin/discordgo/releases/tag/v0.24.0).
![Screenshot 2022-04-10 171033](https://user-images.githubusercontent.com/25107528/162643940-ea14b1b9-468a-4ffa-8dda-ee864a9a133b.png)

**Comment by TannerKvarfordt** [comment]
@TnekRex this should be a pretty straightforward update if you're still interested in contributing! :) If you decide you're interested, let me know and we can go over the details sometime.

**Comment by TnekRex** [comment]
When you're home next time I'll have to have you set up the environment
again. The old desktop was making a bad noise so I rebuild Lindsey's old
laptop to use instead.

**Comment by TannerKvarfordt** [comment]
Closing this for now as it is low priority, and the reset button can be kind of nice to have even if it isn't strictly needed.
